% 20Mg data
[DataManager]
Runs: 31, ..., 40, 47, ..., 64
%Runs: 47, ..., 64
%Exclude:
%Manual: ./Macros/Outputs/gatconf_l1.dat

[Raw]
TreeName: ACTAR_TTree
Path: ./RootFiles/Raw/
Begin: Tree_Run_
End: _Merged

[Cluster]
TreeName: GETTree
Path: ./RootFiles/Cluster/
Begin: Clusters_Run_

[Data]
TreeName: VXITree
Path: ./RootFiles/Data/
Begin: Data_Run_

[Filter]
TreeName: GETTree
Path: ./RootFiles/Filter/
Begin: Filter_Run_

[Merger]
TreeName: ACTAR_Merged
Path: ./RootFiles/Merger/
Begin: Merged_Run_

[Corrector]
TreeName: ACTAR_Merged
Path: ./RootFiles/Corrector/
Begin: Corrected_Run_
