[Actar]
Type: Actar
RebinZ: 4
%%%%%%%%%%%%%%%%%% MEvent -> Data options %%%%%%%%%%%%%%%%%%%%
% Clean duplicated voxels
CleanDuplicatedVoxels: false
% Cleaning of Voxels when reading data
%CleanSaturatedMEvent: true
CleanPadMatrix: false
%CleanSaturatedVoxelsPars: 20, 2000
EnableRawBranchInFilter: false
%%%%%%%%%%%%%%%%%% Data -> Physics options %%%%%%%%%%%%%%%%%%%
% Method to cluster!
ClusterMethod: Continuity
% and method to filter
FilterMethod: MultiAction


[Silicons]
Actions: ./Calibrations/ACTION/ACTIONS_s2008_run31.txt
Layers: f0, f1, l0, r0
%Names sets the equivalence between our keys (Layers) and action ones
Names: F0_, F1_, L0_, R0_

[Modular]
Actions: ./Calibrations/ACTION/ACTIONS_s2008_run31.txt
Names: INCONF, GATCONF, SCA_CFA, CTR_TIMEH_UP, CTR_TIMEH, CTR_TIMEML_UP, CTR_TIMEML, SCA_SIF3

[Merger]
IsEnabled: true
SilSpecsFile: ./configs/silspecs.conf

%%1 Set conditions for analysis
% Force each event to have one of these GATCONF values
ForceGATCONF: true
% gatX : ss -> gat command maps X int to ss layer of Sils, as declared in [Silicons]::Layers command
gat1: l0
gat2: r0
gat4: f0, f1
gat8: L1
% L1 implementation in merger detector is very preliminary and subject to bugs
% Force each event to have a beam-like cluster
% (you usually want this unless calibrating)
ForceBeamLike: true
% Number of non-beam clusters allowed in event
NotBeamMults: 1,2
ForceRP: true

%%2 Enable default beam dir (1, 0, 0) for very short BL
EnableDefaultBeam: false
DefaultBeamXThresh: 10

%%3 Assign cluster to light or heavy particles
%Calculations are usually performed only with light
InvertAngle: false
% And validate L1 on Light
EnableL1Validation: true
L1ExclusionZone: 7

%% Gate on RP X, discarding events with RP.X() < that threshold
%% whose angles cannot be faithfully reconstructed
%% Should be corrected now in MultiStep with EnableDefaultBL option
GateRPX: 0

%%4 Q profiling
EnableQProfile: true
2DProfile: false
% Root finding to determine range from profiles
EnableRootFind: true


%%5 Conversion to physical units
EnableConversion: true
%Drift factor for Z coordinate, which implicitly considers REBINZ factor
DriftFactor: 2.208
% Poorly determined with low stats

%%6 Cleaning of noise by applying match of physical SP with SilSpecs Si coordinates
EnableMatch: false
MatchUseZ: false
ZOffset: 0

%% Task to set vdrift per run -> the value in this file is not used at all
%% as it is overwritten in each event. Sett ConfMergerPerRun plugin
Task0: /configs/user/, ConfMergerPerRun, Before_IsDoable
