[User0]
Name: TopoSplit
Path: /configs/user/

[TopoSplit]
IsEnabled: true
Chi2Thresh: 1.25
IdxOffset: -3
# Too small these windows? [Merge] seems to recover the fragments quite well
BeamWindowY: 2
BeamWindowZ: 2
Debug: true

[BreakChi2]
IsEnabled: false
Chi2Thresh: 2.5
MinXRange: 15
LengthXToBreak:10
FixMaxAngle: 10
FixMinXRange: 90
FixChi2Diff: 1.05
BeamWindowY: 3
BeamWindowZ: 3
BreakLengthThresh: 3
DoClusterNotBeam: true
DoBreakMultiTracks: true
TrackChi2Thresh: 2.5
BeamWindowScale: 2

[Merge]
IsEnabled: true
DistThresh: 4
MinParallelFactor: 0.95
Chi2Factor: 1.5

[User1]
Name: RecRANSAC
Path: /configs/user/

[RecRANSAC]
IsEnabled: true
NIter: 150
MinVoxels: 11
DistThresh: 2

# Call merge again after RANSAC
[Merge]
IsEnabled: true
DistThresh: 4
MinParallelFactor: 0.95
Chi2Factor: 1.5

# [CleanPileUp]
# IsEnabled: true
# XPercent: 0.2
# LowerZ: 210
# UpperZ: 330

[CleanDeltas]
IsEnabled: true
UseExtVoxels: true
Chi2Thresh: 1.9
# Ensure this threshold is lower than in RecRANSAC!!
MaxVoxels: 10
UseCylinder: false
SigmaGap: 2.1
CylinderR: 1.75

[CleanZs]
IsEnabled: true
ZDirectionThreshold: 0.9
MaxSpanInPlane: 8

[CleanBadFits]
IsEnabled: true

[CleanZs]
IsEnabled: true
ZDirectionThreshold: 0.9
MaxSpanInPlane: 8

[FindRP]
IsEnabled: true
UseExtVoxels: true
BeamLikeMaxAngle: 10
BeamLikeXMinThresh: 5
BeamLikeMinVoxels: 15
RPDistThresh: 5
RPDistCluster: 10
RPDistToggleSort: 17
EnableDeleteInvalidCluster: true
# More detailed treatment
EnableFineRP: true
KeepBreakBeam: true
MinXSepBreakBeam: 3
MinVoxelsBreakBeam: 5
EnableRPDefaultBeam: true
RPDefaultMinX: 10
EnableFixBreakBeam: false
MaxVoxelsFixBreak: 95
MinPercentFixBreak: 0.825
EnableCylinder: false
CylinderR: 3
RPMaskXY: 0
RPMaskZ: 0
RPPivotDist: 0
