[f0]
Width: 50.
Height: 50.
Thickness: 1.5
%% iX command explanation
%% iX = index : <x OR y centre point, z point>
i0: 203, 125
i1: 153, 125
i2: 103, 125
i3: 53, 125

i4: 203, 175
i5: 153, 175
i6: 103, 175
i7: 53, 175

i8: 203, 225
i9: 153, 225
i10: 103, 225
i11: 53, 225
% Distance from f0 height minimisation. See DistDebug.cxx
Point: 358.22, 128, 135
Normal: 1, 0, 0
%% One can set a commom threshold in MeV units
CommomThresh: 0.5
%% Or specify one per pad with t command
%% t0: 0.8
%% t1: 0.5
%% Spec of side
Side: front
% Pad in painter
PadIdx: 5
Particle: Light
Mults: 1
MatchMargin: 2.5

[f1]
Width: 50.
Height: 50.
Thickness: 1.5
i0: 203, 125
i1: 153, 125
i2: 103, 125
i3: 53, 125

i4: 203, 175
i5: 153, 175
i6: 103, 175
i7: 53, 175

i8: 203, 225
i9: 153, 225
i10: 103, 225
i11: 53, 225
% Distance from f0 height minimisation. See DistDebug.cxx
% Assumed 6.82 mm offset between layers...
% We were told this during the exp... for sure need to check
Point: 383.22, 128, 135
Normal: 1, 0, 0
%CommomThresh: 0.5
% Disable sils 8 and 10 that are noisy
t0: 0.5
t1: 0.5
t2: 0.5
t3: 0.5
t4: 0.5
t5: 0.5
t6: 0.5
t7: 0.5
t8: 100.
t9: 0.5
t10: 100.
t11: 0.5
Side: front
PadIdx: 6
Particle: Light
Mults: 1
MatchMargin: 2.5


[l0]
Width: 80.
Height: 50.
Thickness: 0.5
%% iX command explanation
%% iX = index : <x OR y centre point, z point>
i2: 208, 25
i1: 128, 25
i0: 48, 25

i5: 208, 75
i4: 128, 75
i3: 48, 75

i8: 208, 125
i7: 128, 125
i6: 48, 125

i11: 208, 175
i10: 128, 175
i9: 48, 175
%% Point is referred to origin of pad plane
%% this layer is along Y
% Distance from minimisation
Point: 128, 334.37, 100
Normal: 0, 1, 0
%% One can set a commom threshold in MeV units
CommomThresh: 0.5
%% Spec of side
Side: left
% Pad in painter
PadIdx: 1
Particle: Light
Mults: 1
MatchMargin: 2.5


[r0]
Width: 80.
Height: 50.
Thickness: 0.5
%% iX command explanation
%% iX = index : <x OR y centre point, z point>
i0: 208, 25
i1: 128, 25
i2: 48, 25

i3: 208, 75
i4: 128, 75
i5: 48, 75

i6: 208, 125
i7: 128, 125
i8: 48, 125

i9: 208, 175
i10: 128, 175
i11: 48, 175
%% Point is referred to origin of pad plane
%% this layer is along Y
% Distance from minimisation
Point: 128, -82.49, 100
Normal: 0, -1, 0
%% One can set a commom threshold in MeV units
CommomThresh: 0.5
%% Spec of side
Side: right
% Pad in painter
PadIdx: 7
Particle: Light
Mults: 1
MatchMargin: 2.5
